### ISSUE TITLE
Loki components stuck on `CrashLoopBackOff` when deploying example manifests on GKE

### ISSUE THREAD

**Issue by ArthurSens** [observatorium/observatorium#410]
Yesterday I was trying to deploy Observatorium on a fresh new GKE cluster.

To deploy Observatorium I followed the [e2e test script in the operator repository](https://github.com/observatorium/operator/blob/master/tests/e2e.sh).

The components `loki-compactor`, `loki-ingester` and `loki-querier` got stuck on `CrashLoopBackOff`, all with the same error:
```
level=error ts=2021-05-06T20:07:23.034407503Z caller=log.go:149 msg="error running loki" err="mkdir /data/loki: permission denied
```

After manually editing their statefulsets, adding the `securityContext` below it worked just fine:
```
      securityContext: 
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
```

Of course, this is not the safest approach, but I was expecting that those manifests would work on any Kubernetes cluster without manual intervention. Should I make adjustments somewhere?

**Comment by ArthurSens** [comment]
Just noticed that the same thing happens to Dex deployment as well

**Comment by periklis** [comment]
@ArthurSens This sounds strange because the `/data` directory is a persistent volume with `ReadWriteOnce` access mode. Changing the security context to access the volume sounds like brute force. Can you elaborate on your GKE configuration? Especially take a look on the default `StorageClass` used for Loki's PVCs.

**Comment by bigon** [comment]
Any idea? I'm still seeing that when deploying on EKS

**Comment by bigon** [comment]
I can confirm that adding a `securityContext` to the container fixed the problem for me here, even with `runAsNonRoot` set as true

```yaml
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
```
